export const GET_ALL_POSTS = 'GET_ALL_POSTS';
export const SET_ALL_POSTS = 'SET_ALL_POSTS';
export const GET_PAGINATED_POSTS = 'GET_PAGINATED_POSTS';
export const SET_PAGINATED_POSTS = 'SET_PAGINATED_POSTS';
export const UPVOTE_POST = 'UPVOTE_POST';
export const DOWNVOTE_POST = 'DOWNVOTE_POST';
export const UPDATE_POST = 'UPDATE_POST';
export const UNVOTE_POST = 'UNVOTE_POST';
