export const GET_ALL_USERS = 'GET_ALL_USERS';
export const SET_ALL_USERS = 'SET_ALL_USERS';
export const DELETE_USER_BY_ID = 'DELETE_USER_BY_ID';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
