export const GET_POSTS_BY_USERNAME = 'GET_POSTS_BY_USERNAME';
export const SET_POSTS_BY_USERNAME = 'SET_POSTS_BY_USERNAME';
export const GET_USER_BY_USERNAME = 'GET_USER_BY_USERNAME';
export const SET_USER_BY_USERNAME = 'SET_USER_BY_USERNAME';
